-- Auto-generated from schema-map-postgres.yaml (map@sha1:8C4F2BC1C4D22EE71E27B5A7968C71E32D8D884D)
-- engine: postgres
-- table:  slo_windows

CREATE TABLE IF NOT EXISTS slo_windows (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  objective JSONB NOT NULL,                     -- {"metric":"outbox_latency_sec","threshold":10,"percentile":95}
  target_pct NUMERIC(5,2) NOT NULL,
  window_interval INTERVAL NOT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);
