-- Auto-generated from schema-map-postgres.yaml (map@sha1:6D9B52237D942B2B3855FD0F5500331B935A7C62)
-- engine: postgres
-- table:  slo_windows

CREATE TABLE IF NOT EXISTS slo_windows (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  objective JSONB NOT NULL,                     -- {"metric":"outbox_latency_sec","threshold":10,"percentile":95}
  target_pct NUMERIC(5,2) NOT NULL,
  window_interval INTERVAL NOT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);
