-- Auto-generated from schema-map-postgres.psd1 (map@62c9c93)
-- engine: postgres
-- table:  slo_windows
CREATE TABLE IF NOT EXISTS slo_windows (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL UNIQUE,
  objective JSONB NOT NULL,                     -- {"metric":"outbox_latency_sec","threshold":10,"percentile":95}
  target_pct NUMERIC(5,2) NOT NULL,
  window_interval INTERVAL NOT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);
